# Generated by Django 6.0.3 on 2026-05-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('point', models.IntegerField(default=1)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
