# Generated by Django 6.0.3 on 2026-06-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพ')),
                ('others', models.CharField(blank=True, null=True, verbose_name='อื่นๆ')),
            ],
        ),
    ]
